# Generated by Django 4.1.6 on 2023-03-19 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="code",
            field=models.CharField(default="0", max_length=6),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 12, 45, 23, 199889, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 19, 12, 45, 23, 200889, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
