# Generated by Django 4.1.6 on 2023-03-24 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(default='0', max_length=75),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 23, 9, 52, 843377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
